# Generated by Django 3.2.7 on 2022-06-05 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_auto_20220605_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulfillment',
            name='visit',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='visits.visit'),
        ),
    ]
