# Generated by Django 3.2.7 on 2022-06-05 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_fulfillment_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulfillment',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fulfillment',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='visits.visit'),
        ),
    ]
