# Generated by Django 3.2.7 on 2022-06-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_auto_20220605_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='pal',
            name='banked_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
