# Generated by Django 3.2.7 on 2022-06-06 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0005_pal_banked_minutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulfillment',
            name='notes',
        ),
    ]
