# Generated by Django 3.2.7 on 2022-06-06 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0006_remove_fulfillment_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pal',
            name='banked_minutes',
        ),
    ]
