# Generated by Django 3.2.7 on 2022-06-07 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0008_minuteledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minuteledger',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='minuteledger',
            name='reason',
            field=models.CharField(choices=[('visit_scheduled', 'Member scheduled a visit'), ('visit_fulfilled', 'Pal completed a visit')], max_length=100),
        ),
        migrations.AlterField(
            model_name='minuteledger',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.visit'),
        ),
    ]
